name: thesis-cbm
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pip
  - numpy
  - pytorch::pytorch
  - torchaudio
  - cudatoolkit=11.8
  - pip:
      - transformers>=4.44
      - datasets>=2.20
      - soundfile>=0.12
      - pyyaml>=6.0
