name: thesis-cbm
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - pip
  - numpy==1.23.5
  - pandas
  - matplotlib
  - scikit-learn
  - tqdm
  - librosa
  - ipython
  - pytorch
  - torchvision
  - torchaudio
  - pip:
    - datasets==1.18.3
    - pyarrow==6.0.1
    - transformers
    - jiwer
    - accelerate>=0.26.0
  - wandb
