name: thesis-cbm
channels:
  - pytorch
  - nvidia
  - conda-forge
dependencies:
  - python=3.9
  - numpy=1.23.5
  - pandas
  - matplotlib
  - scikit-learn
  - tqdm
  - librosa
  - ipython
  - pytorch
  - torchvision
  - torchaudio
  - pytorch-cuda=11.8  # Specify your CUDA version for the A100s
  - wandb
  - pip
  - pip:
    - datasets==1.18.3
    - pyarrow==6.0.1
    - transformers
    - jiwer
    - accelerate>=0.26.0